---
- name: Floating ip | Assign ip script
  copy:
    src: assign-ip
    dest: /usr/local/bin/assign-ip
    owner: root
    group: root
    mode: '0755'

- name: Systemd | Create systemd service
  template:
      src: assign-ip.service.j2
      dest: /etc/init.d/assign-ip
      mode: '0755'
      owner: 'root'
      group: 'root'
  when: "'floating_ip' in groups" 
