---
# tasks file for heartbeat
- name: Install | Install heartbeat package
  import_tasks: install_heartbeat.yml 

- name: Configuration | Configure ha.cf file
  import_tasks: configure_hacf.yml

- name: Configuration | Configure Authkeys
  import_tasks: authkeys.yml

- name: Configuration | Configure haresources
  import_tasks: haresources.yml

- name: Enable Heartbeat service
  systemd:
    name: heartbeat
    enabled: yes
